### ISSUE TITLE
画像以外のリンクの記述でbase64処理しようとしてる

### ISSUE THREAD

**Issue by nakajmg** [nakajmg/cgmd-browser#7]
![image](https://cloud.githubusercontent.com/assets/1995370/19867580/b12f6a7c-9fe7-11e6-906b-cd21ebe252a3.png)

<details>
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/local/work/pxg/codegrid-draft/drafts/2016-vue/demo/2/1/styles.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at file.replace (/Applications/cgmd-browser.app/Contents/Resources/app/electron.js:244:20)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at openMarkdown (/Applications/cgmd-browser.app/Contents/Resources/app/electron.js:242:31)
    at EventEmitter.ipcMain.on (/Applications/cgmd-browser.app/Contents/Resources/app/electron.js:322:5)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Applications/cgmd-browser.app/Contents/Resources/electron.asar/browser/api/web-contents.js:210:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
</details>

**Comment by nakajmg** [comment]
#8
